version: "3.9"
services:
  agentm:
    build: .
    container_name: agentm
    ports:
      - "8000:8000"
    env_file:
      - .env
      - agent/.env
    restart: unless-stopped
    volumes:
      - ./model_cache:/app/model_cache
      - ./rag_cache:/app/rag_cache
    environment:
      - HF_HOME=/app/model_cache